import 'chemical_element.dart';

const kPeriodicElements = <ChemicalElement>[
  ChemicalElement(
    1,
    'H',
    'Hydrogen',
    1.008,
    'nonmetal',
    'The most abundant element in the universe, making up about 75% of all matter.',
    'Hydrogen was once used to fill airships, but it is highly flammable.',
  ),
  ChemicalElement(
    2,
    'He',
    'Helium',
    4.003,
    'noble',
    'A colorless, odorless noble gas — the second most abundant element in the universe.',
    'Helium makes your voice squeaky because sound travels faster through it.',
  ),
  ChemicalElement(
    3,
    'Li',
    'Lithium',
    6.941,
    'alkali',
    'The lightest of all metals, used in batteries and mood-stabilizing medicine.',
    'Lithium batteries power most smartphones and electric cars.',
  ),
  ChemicalElement(
    4,
    'Be',
    'Beryllium',
    9.012,
    'alkaline',
    'A strong, light metal used in aerospace components and X-ray equipment.',
    'Beryllium is so stiff it is used to make satellite mirrors.',
  ),
  ChemicalElement(
    5,
    'B',
    'Boron',
    10.811,
    'metalloid',
    'A metalloid essential for plant growth and used in glass-making.',
    'Borax, a boron compound, has been used as a cleaner for centuries.',
  ),
  ChemicalElement(
    6,
    'C',
    'Carbon',
    12.011,
    'nonmetal',
    'The building block of all life, found in every living thing on Earth.',
    'Diamonds and pencil graphite are both made of pure carbon.',
  ),
  ChemicalElement(
    7,
    'N',
    'Nitrogen',
    14.007,
    'nonmetal',
    'Makes up 78% of Earth\'s atmosphere and is vital for all living things.',
    'Liquid nitrogen (-196°C) can instantly freeze food solid.',
  ),
  ChemicalElement(
    8,
    'O',
    'Oxygen',
    15.999,
    'nonmetal',
    'Essential for breathing and combustion, making up 21% of Earth\'s atmosphere.',
    'Oxygen was discovered independently by two scientists in 1774.',
  ),
  ChemicalElement(
    9,
    'F',
    'Fluorine',
    18.998,
    'halogen',
    'The most reactive element, used to make Teflon non-stick coating and toothpaste.',
    'Fluorine is so reactive it can make some noble gases form compounds.',
  ),
  ChemicalElement(
    10,
    'Ne',
    'Neon',
    20.180,
    'noble',
    'A colorless, inert gas that glows bright orange-red in electrical discharge.',
    'Pure neon actually glows red — most "neon" signs use other gases.',
  ),
  ChemicalElement(
    11,
    'Na',
    'Sodium',
    22.990,
    'alkali',
    'A soft, silvery metal that reacts violently with water, forming salt with chlorine.',
    'The yellow glow of street lights comes from sodium vapor lamps.',
  ),
  ChemicalElement(
    12,
    'Mg',
    'Magnesium',
    24.305,
    'alkaline',
    'A light, strong metal used in aircraft parts and essential for plant life (chlorophyll).',
    'Magnesium burns with an intense white light, even underwater.',
  ),
  ChemicalElement(
    13,
    'Al',
    'Aluminum',
    26.982,
    'post',
    'The most abundant metal in Earth\'s crust, lightweight and resistant to corrosion.',
    'Napoleon used aluminum cutlery for special guests — it was once rarer than gold.',
  ),
  ChemicalElement(
    14,
    'Si',
    'Silicon',
    28.086,
    'metalloid',
    'The second most abundant element in Earth\'s crust, used to make computer chips.',
    'Silicon Valley is named after this element because of its use in microchips.',
  ),
  ChemicalElement(
    15,
    'P',
    'Phosphorus',
    30.974,
    'nonmetal',
    'Essential for life, found in DNA, bones, and used in fertilizers.',
    'Phosphorus was first extracted from urine in 1669 by an alchemist seeking gold.',
  ),
  ChemicalElement(
    16,
    'S',
    'Sulfur',
    32.065,
    'nonmetal',
    'A yellow solid used in gunpowder, medicine, and rubber vulcanization.',
    'Sulfur is found in pure form near volcanoes — it has a distinctive smell.',
  ),
  ChemicalElement(
    17,
    'Cl',
    'Chlorine',
    35.453,
    'halogen',
    'A greenish-yellow gas used to disinfect water and make household cleaners.',
    'Chlorine was used as a chemical weapon in World War I.',
  ),
  ChemicalElement(
    18,
    'Ar',
    'Argon',
    39.948,
    'noble',
    'The third most abundant gas in Earth\'s atmosphere, used in welding and light bulbs.',
    'Argon\'s name comes from the Greek for "lazy" — it rarely reacts.',
  ),
  ChemicalElement(
    19,
    'K',
    'Potassium',
    39.098,
    'alkali',
    'An essential element for health, regulating fluid balance and nerve signals.',
    'Bananas are famously rich in potassium.',
  ),
  ChemicalElement(
    20,
    'Ca',
    'Calcium',
    40.078,
    'alkaline',
    'The most abundant mineral in the body, found in bones, teeth, and muscles.',
    'Calcium makes up about 2% of adult body weight — mostly in your skeleton.',
  ),
  ChemicalElement(
    21,
    'Sc',
    'Scandium',
    44.956,
    'transition',
    'A rare, silvery metal used in aerospace components and high-intensity lights.',
    'Scandium was discovered in Scandinavia — hence its name.',
  ),
  ChemicalElement(
    22,
    'Ti',
    'Titanium',
    47.867,
    'transition',
    'A strong, lightweight metal used in aircraft, medical implants, and jewelry.',
    'Titanium is as strong as steel but 45% lighter.',
  ),
  ChemicalElement(
    23,
    'V',
    'Vanadium',
    50.942,
    'transition',
    'A hard, silvery-grey metal used to strengthen steel alloys.',
    'Vanadium steel was used to build the Ford Model T — stronger and cheaper.',
  ),
  ChemicalElement(
    24,
    'Cr',
    'Chromium',
    51.996,
    'transition',
    'A shiny, hard metal used to make stainless steel and chrome-plated surfaces.',
    'Chrome plating is just a thin layer of chromium for shine and rust resistance.',
  ),
  ChemicalElement(
    25,
    'Mn',
    'Manganese',
    54.938,
    'transition',
    'A metal essential for steel production and important for brain function.',
    'Manganese is essential for the enzymes that keep your brain working.',
  ),
  ChemicalElement(
    26,
    'Fe',
    'Iron',
    55.845,
    'transition',
    'One of Earth\'s most abundant metals, essential for blood and used to make steel.',
    'The Earth\'s core is mostly iron, which creates our planet\'s magnetic field.',
  ),
  ChemicalElement(
    27,
    'Co',
    'Cobalt',
    58.933,
    'transition',
    'A magnetic metal used in batteries, alloys, and to create vivid blue pigments.',
    'The brilliant blue in ancient glass and ceramics comes from cobalt.',
  ),
  ChemicalElement(
    28,
    'Ni',
    'Nickel',
    58.693,
    'transition',
    'A hard, silvery metal used in coins, stainless steel, and batteries.',
    'The US 5-cent "nickel" coin contains more copper than nickel.',
  ),
  ChemicalElement(
    29,
    'Cu',
    'Copper',
    63.546,
    'transition',
    'An excellent conductor of electricity, used in wiring and plumbing since ancient times.',
    'The Statue of Liberty is made of copper and turned green due to oxidation.',
  ),
  ChemicalElement(
    30,
    'Zn',
    'Zinc',
    65.38,
    'transition',
    'A bluish-white metal used to galvanize steel and essential for immune function.',
    'Zinc deficiency affects about 2 billion people worldwide.',
  ),
  ChemicalElement(
    31,
    'Ga',
    'Gallium',
    69.723,
    'post',
    'A soft metal that melts in your hand (at 29.76°C), used in semiconductors and LEDs.',
    'Gallium melts just above room temperature — it will melt in your palm!',
  ),
  ChemicalElement(
    32,
    'Ge',
    'Germanium',
    72.630,
    'metalloid',
    'A metalloid used in fiber optics and infrared optical systems.',
    'Germanium was predicted by Mendeleev before it was even discovered.',
  ),
  ChemicalElement(
    33,
    'As',
    'Arsenic',
    74.922,
    'metalloid',
    'A toxic metalloid historically used as poison, now used in semiconductors.',
    'Victorian wallpapers often contained arsenic pigments — poisoning many people.',
  ),
  ChemicalElement(
    34,
    'Se',
    'Selenium',
    78.971,
    'nonmetal',
    'A nonmetal essential in small amounts for health, used in solar cells.',
    'Selenium gives glass a red tint — it cancels out an unwanted green tint.',
  ),
  ChemicalElement(
    35,
    'Br',
    'Bromine',
    79.904,
    'halogen',
    'One of only two elements liquid at room temperature — a reddish-brown toxic liquid.',
    'Bromine\'s name comes from Greek for "stench" due to its strong smell.',
  ),
  ChemicalElement(
    36,
    'Kr',
    'Krypton',
    83.798,
    'noble',
    'A noble gas used in high-performance lighting and laser technology.',
    'Krypton is Superman\'s home planet — but real krypton is just a boring noble gas!',
  ),
  ChemicalElement(
    37,
    'Rb',
    'Rubidium',
    85.468,
    'alkali',
    'A soft, silvery metal that ignites spontaneously in air.',
    'Rubidium clocks are among the most precise timekeepers in the world.',
  ),
  ChemicalElement(
    38,
    'Sr',
    'Strontium',
    87.62,
    'alkaline',
    'An alkaline earth metal that burns with a crimson flame.',
    'Strontium compounds give fireworks their brilliant red color.',
  ),
  ChemicalElement(
    39,
    'Y',
    'Yttrium',
    88.906,
    'transition',
    'A silvery metal used in LEDs, laser crystals, and superconductors.',
    'Yttrium, ytterbium, terbium, and erbium are all named after the same village.',
  ),
  ChemicalElement(
    40,
    'Zr',
    'Zirconium',
    91.224,
    'transition',
    'A strong, corrosion-resistant metal used in nuclear reactors and jewelry.',
    'Cubic zirconia, a fake diamond, is made from zirconium oxide.',
  ),
  ChemicalElement(
    41,
    'Nb',
    'Niobium',
    92.906,
    'transition',
    'A soft, grey metal used in superalloys for jet engines.',
    'Niobium is used in the Large Hadron Collider\'s superconducting magnets.',
  ),
  ChemicalElement(
    42,
    'Mo',
    'Molybdenum',
    95.96,
    'transition',
    'A silvery metal that adds strength and hardness to steel alloys.',
    'Some bacteria use molybdenum to convert nitrogen gas into ammonia.',
  ),
  ChemicalElement(
    43,
    'Tc',
    'Technetium',
    97.0,
    'transition',
    'The lightest element with no stable isotopes — all isotopes are radioactive.',
    'Technetium was the first artificially produced element.',
  ),
  ChemicalElement(
    44,
    'Ru',
    'Ruthenium',
    101.07,
    'transition',
    'A rare platinum-group metal used in electrical contacts and catalysts.',
    'Ruthenium can harden platinum and palladium for use in jewelry.',
  ),
  ChemicalElement(
    45,
    'Rh',
    'Rhodium',
    102.906,
    'transition',
    'The rarest and most expensive precious metal, used in catalytic converters.',
    'Rhodium is about 10–25 times more expensive than gold.',
  ),
  ChemicalElement(
    46,
    'Pd',
    'Palladium',
    106.42,
    'transition',
    'A precious metal used in catalytic converters and electronics.',
    'Palladium can absorb 900 times its own volume of hydrogen gas.',
  ),
  ChemicalElement(
    47,
    'Ag',
    'Silver',
    107.868,
    'transition',
    'A shiny precious metal with the highest electrical conductivity of all elements.',
    'Silver has been used as money for over 4,000 years.',
  ),
  ChemicalElement(
    48,
    'Cd',
    'Cadmium',
    112.411,
    'transition',
    'A soft, bluish-white metal used in rechargeable batteries and pigments.',
    'Cadmium yellow was a favorite color of Impressionist painters like Monet.',
  ),
  ChemicalElement(
    49,
    'In',
    'Indium',
    114.818,
    'post',
    'A soft, silvery metal used in touchscreens and flat panel displays.',
    'The touchscreen on your phone likely contains indium tin oxide.',
  ),
  ChemicalElement(
    50,
    'Sn',
    'Tin',
    118.710,
    'post',
    'A silvery metal used since ancient times to make bronze (with copper).',
    'Tin cans are mostly steel — just coated with tin to prevent rust.',
  ),
  ChemicalElement(
    51,
    'Sb',
    'Antimony',
    121.760,
    'metalloid',
    'A metalloid used in flame retardants and semiconductor devices.',
    'Ancient Egyptians used antimony sulfide as black eye makeup.',
  ),
  ChemicalElement(
    52,
    'Te',
    'Tellurium',
    127.60,
    'metalloid',
    'A brittle, silver-white metalloid used in solar panels and optical discs.',
    'Tellurium is one of the rarest stable elements in Earth\'s crust.',
  ),
  ChemicalElement(
    53,
    'I',
    'Iodine',
    126.904,
    'halogen',
    'An essential nutrient for thyroid hormones, also used as a disinfectant.',
    'Iodine\'s name comes from Greek for "violet" — its vapor is purple.',
  ),
  ChemicalElement(
    54,
    'Xe',
    'Xenon',
    131.293,
    'noble',
    'A noble gas used in high-intensity lamps, lasers, and as an anesthetic.',
    'Xenon headlights in cars produce a distinctive bright blue-white light.',
  ),
  ChemicalElement(
    55,
    'Cs',
    'Cesium',
    132.905,
    'alkali',
    'The softest metal and most reactive alkali metal, used in atomic clocks.',
    'The second (unit of time) is defined using cesium atomic vibrations.',
  ),
  ChemicalElement(
    56,
    'Ba',
    'Barium',
    137.327,
    'alkaline',
    'A soft, silvery metal used in medical imaging (barium meal X-rays).',
    'Barium sulfate is swallowed by patients before stomach X-rays — it\'s non-toxic.',
  ),
  ChemicalElement(
    57,
    'La',
    'Lanthanum',
    138.905,
    'lanthanide',
    'The first lanthanide element, used in camera lenses and hydrogen storage.',
    'Lanthanum compounds make night-vision goggles possible.',
  ),
  ChemicalElement(
    58,
    'Ce',
    'Cerium',
    140.116,
    'lanthanide',
    'The most abundant rare earth element, used in catalytic converters and lighter flints.',
    'The sparks from a lighter flint are caused by cerium alloy.',
  ),
  ChemicalElement(
    59,
    'Pr',
    'Praseodymium',
    140.908,
    'lanthanide',
    'A soft, silvery metal used in high-strength magnets and welder\'s goggles.',
    'Praseodymium gives glass a distinctive yellow-green color.',
  ),
  ChemicalElement(
    60,
    'Nd',
    'Neodymium',
    144.242,
    'lanthanide',
    'Used to make the strongest permanent magnets in the world.',
    'Neodymium magnets are so powerful they can be dangerous if mishandled.',
  ),
  ChemicalElement(
    61,
    'Pm',
    'Promethium',
    145.0,
    'lanthanide',
    'A radioactive element used in early pacemakers and spacecraft power sources.',
    'Promethium is named after Prometheus, who stole fire from the gods.',
  ),
  ChemicalElement(
    62,
    'Sm',
    'Samarium',
    150.36,
    'lanthanide',
    'A hard, silvery metal used in magnets, cancer treatment, and lasers.',
    'Samarium-cobalt magnets work at higher temperatures than neodymium magnets.',
  ),
  ChemicalElement(
    63,
    'Eu',
    'Europium',
    151.964,
    'lanthanide',
    'A rare earth element used in fluorescent lamps and euro banknote security features.',
    'The red and blue colors in TV screens and monitors use europium compounds.',
  ),
  ChemicalElement(
    64,
    'Gd',
    'Gadolinium',
    157.25,
    'lanthanide',
    'Used as a contrast agent in MRI scans and in nuclear reactor control rods.',
    'Gadolinium has one of the highest neutron-capture cross-sections of all elements.',
  ),
  ChemicalElement(
    65,
    'Tb',
    'Terbium',
    158.925,
    'lanthanide',
    'A soft, silvery rare earth metal used in solid-state devices and sonar.',
    'Terbium can expand and contract when placed in a magnetic field.',
  ),
  ChemicalElement(
    66,
    'Dy',
    'Dysprosium',
    162.5,
    'lanthanide',
    'A rare earth metal used in electric motors of electric vehicles and wind turbines.',
    'Dysprosium\'s name comes from Greek for "hard to get."',
  ),
  ChemicalElement(
    67,
    'Ho',
    'Holmium',
    164.930,
    'lanthanide',
    'Has the strongest magnetic moment of any naturally occurring element.',
    'Holmium is used in nuclear reactors to help control the chain reaction.',
  ),
  ChemicalElement(
    68,
    'Er',
    'Erbium',
    167.259,
    'lanthanide',
    'A soft, silvery metal used in fiber optic cables and laser surgery.',
    'Erbium amplifiers boost signals in long-distance fiber optic cables.',
  ),
  ChemicalElement(
    69,
    'Tm',
    'Thulium',
    168.934,
    'lanthanide',
    'A rare earth metal used in portable X-ray machines and lasers.',
    'Thulium is the rarest naturally occurring lanthanide.',
  ),
  ChemicalElement(
    70,
    'Yb',
    'Ytterbium',
    173.054,
    'lanthanide',
    'Used in the most precise atomic clocks and as a dopant in fiber optic cables.',
    'Ytterbium clocks would lose 1 second in 10 billion years.',
  ),
  ChemicalElement(
    71,
    'Lu',
    'Lutetium',
    174.967,
    'lanthanide',
    'The heaviest and hardest rare earth metal, used in PET scan detectors.',
    'Lutetium is named after Lutetia, the ancient Latin name for Paris.',
  ),
  ChemicalElement(
    72,
    'Hf',
    'Hafnium',
    178.49,
    'transition',
    'A shiny, corrosion-resistant metal used in nuclear reactor control rods.',
    'Hafnium is almost always found with zirconium — they are very hard to separate.',
  ),
  ChemicalElement(
    73,
    'Ta',
    'Tantalum',
    180.948,
    'transition',
    'A hard, corrosion-resistant metal used in electronics and surgical instruments.',
    'Tantalum capacitors are in virtually every electronic device.',
  ),
  ChemicalElement(
    74,
    'W',
    'Tungsten',
    183.84,
    'transition',
    'The element with the highest melting point (3,422°C), used in light bulb filaments.',
    'Tungsten\'s chemical symbol W comes from its old name "wolfram."',
  ),
  ChemicalElement(
    75,
    'Re',
    'Rhenium',
    186.207,
    'transition',
    'One of the rarest elements on Earth, used in jet engine turbine blades.',
    'Rhenium has the second highest melting point of all elements.',
  ),
  ChemicalElement(
    76,
    'Os',
    'Osmium',
    190.23,
    'transition',
    'The densest naturally occurring element — a baseball-sized piece weighs 14 kg.',
    'Osmium tetroxide has a distinctive and dangerous pungent smell.',
  ),
  ChemicalElement(
    77,
    'Ir',
    'Iridium',
    192.217,
    'transition',
    'The most corrosion-resistant metal, used in fountain pen nibs and spark plugs.',
    'A layer of iridium in Earth\'s crust marks the asteroid that killed the dinosaurs.',
  ),
  ChemicalElement(
    78,
    'Pt',
    'Platinum',
    195.084,
    'transition',
    'A precious metal used in jewelry, catalytic converters, and cancer drugs.',
    'All platinum ever mined would fill a room 25 feet cubed.',
  ),
  ChemicalElement(
    79,
    'Au',
    'Gold',
    196.967,
    'transition',
    'A shiny precious metal that never tarnishes, valued throughout human history.',
    'All gold on Earth came from meteorites — it sank to the core during formation.',
  ),
  ChemicalElement(
    80,
    'Hg',
    'Mercury',
    200.592,
    'transition',
    'The only metal that is liquid at room temperature, used in thermometers.',
    'Mercury\'s symbol Hg comes from "hydrargyrum" — Greek for "liquid silver."',
  ),
  ChemicalElement(
    81,
    'Tl',
    'Thallium',
    204.383,
    'post',
    'A soft, grey post-transition metal — highly toxic, once used as rat poison.',
    'Thallium was the poison of choice in several notorious murder cases.',
  ),
  ChemicalElement(
    82,
    'Pb',
    'Lead',
    207.2,
    'post',
    'A dense, soft metal used in batteries, pipes, and radiation shielding.',
    'Ancient Romans used lead extensively in pipes, pots, and even wine sweeteners.',
  ),
  ChemicalElement(
    83,
    'Bi',
    'Bismuth',
    208.980,
    'post',
    'The least toxic heavy metal, used in cosmetics, medicines, and as a lead substitute.',
    'Bismuth crystals form beautiful rainbow-colored geometric staircase shapes.',
  ),
  ChemicalElement(
    84,
    'Po',
    'Polonium',
    209.0,
    'metalloid',
    'A highly radioactive metalloid famously used in a high-profile assassination.',
    'Marie Curie named polonium after her homeland, Poland.',
  ),
  ChemicalElement(
    85,
    'At',
    'Astatine',
    210.0,
    'halogen',
    'The rarest naturally occurring element — less than 1 gram exists in Earth\'s crust.',
    'Astatine is so rare it has never been seen in bulk — only isolated atoms.',
  ),
  ChemicalElement(
    86,
    'Rn',
    'Radon',
    222.0,
    'noble',
    'A naturally occurring radioactive gas that can accumulate in buildings.',
    'Radon is the second leading cause of lung cancer after smoking.',
  ),
  ChemicalElement(
    87,
    'Fr',
    'Francium',
    223.0,
    'alkali',
    'The second rarest natural element and most unstable of the first 101 elements.',
    'At any moment, less than 30 grams of francium exists in Earth\'s crust.',
  ),
  ChemicalElement(
    88,
    'Ra',
    'Radium',
    226.0,
    'alkaline',
    'A highly radioactive metal discovered by Marie Curie, once used in luminous paint.',
    '"Radium Girls" painted watch dials and suffered severe radiation poisoning.',
  ),
  ChemicalElement(
    89,
    'Ac',
    'Actinium',
    227.0,
    'actinide',
    'A radioactive silvery metal that glows blue in the dark due to radioactivity.',
    'Actinium glows blue because it ionizes the surrounding air.',
  ),
  ChemicalElement(
    90,
    'Th',
    'Thorium',
    232.038,
    'actinide',
    'A radioactive metal proposed as a safer alternative nuclear fuel to uranium.',
    'India has the world\'s largest deposits of thorium sand.',
  ),
  ChemicalElement(
    91,
    'Pa',
    'Protactinium',
    231.036,
    'actinide',
    'A rare, highly radioactive element with limited practical use.',
    'Only about 125 grams of protactinium exist for research purposes worldwide.',
  ),
  ChemicalElement(
    92,
    'U',
    'Uranium',
    238.029,
    'actinide',
    'A dense, radioactive metal used as fuel in nuclear power plants.',
    'Uranium\'s radioactivity was discovered when it accidentally fogged a photo plate.',
  ),
  ChemicalElement(
    93,
    'Np',
    'Neptunium',
    237.0,
    'actinide',
    'The first synthetic transuranium element, produced in nuclear reactors.',
    'Neptunium is named after Neptune, just as uranium is named after Uranus.',
  ),
  ChemicalElement(
    94,
    'Pu',
    'Plutonium',
    244.0,
    'actinide',
    'A fissile material used in nuclear weapons and as fuel in nuclear reactors.',
    'The plutonium for the first atomic bomb came from a secret city in Washington state.',
  ),
  ChemicalElement(
    95,
    'Am',
    'Americium',
    243.0,
    'actinide',
    'A synthetic radioactive metal — tiny amounts are used in home smoke detectors.',
    'There is a tiny amount of americium in every ionization smoke detector.',
  ),
  ChemicalElement(
    96,
    'Cm',
    'Curium',
    247.0,
    'actinide',
    'A radioactive metal named after Marie and Pierre Curie.',
    'Curium glows red hot due to its intense radioactive decay heat.',
  ),
  ChemicalElement(
    97,
    'Bk',
    'Berkelium',
    247.0,
    'actinide',
    'A synthetic radioactive element produced in tiny amounts in nuclear reactors.',
    'Berkelium is named after Berkeley, California, where it was synthesized.',
  ),
  ChemicalElement(
    98,
    'Cf',
    'Californium',
    251.0,
    'actinide',
    'A synthetic radioactive element used in nuclear reactors and cancer treatment.',
    'Californium-252 costs over \$27 million per gram — one of the priciest materials.',
  ),
  ChemicalElement(
    99,
    'Es',
    'Einsteinium',
    252.0,
    'actinide',
    'A synthetic element discovered in the debris of the first hydrogen bomb test.',
    'Einsteinium was discovered secretly during the Cold War.',
  ),
  ChemicalElement(
    100,
    'Fm',
    'Fermium',
    257.0,
    'actinide',
    'A synthetic radioactive element also found in hydrogen bomb fallout.',
    'Fermium is named after Enrico Fermi, who built the first nuclear reactor.',
  ),
  ChemicalElement(
    101,
    'Md',
    'Mendelevium',
    258.0,
    'actinide',
    'A synthetic element named after Mendeleev, creator of the periodic table.',
    'Only a few atoms of mendelevium have ever been produced at one time.',
  ),
  ChemicalElement(
    102,
    'No',
    'Nobelium',
    259.0,
    'actinide',
    'A synthetic radioactive element named after Alfred Nobel.',
    'Nobelium was the subject of a naming dispute between Soviet and American scientists.',
  ),
  ChemicalElement(
    103,
    'Lr',
    'Lawrencium',
    262.0,
    'actinide',
    'The last actinide element, named after Ernest Lawrence, inventor of the cyclotron.',
    'Lawrencium completes the actinide series at atomic number 103.',
  ),
  ChemicalElement(
    104,
    'Rf',
    'Rutherfordium',
    267.0,
    'transition',
    'A synthetic element and the first of the transactinide series.',
    'Rutherfordium is named after physicist Ernest Rutherford.',
  ),
  ChemicalElement(
    105,
    'Db',
    'Dubnium',
    268.0,
    'transition',
    'A highly radioactive synthetic element with a very short half-life.',
    'Dubnium is named after Dubna, Russia, where it was first synthesized.',
  ),
  ChemicalElement(
    106,
    'Sg',
    'Seaborgium',
    271.0,
    'transition',
    'Named after Glenn Seaborg — the only element named after a living person at the time.',
    'Glenn Seaborg co-discovered 10 elements — a record.',
  ),
  ChemicalElement(
    107,
    'Bh',
    'Bohrium',
    272.0,
    'transition',
    'A radioactive synthetic element named after physicist Niels Bohr.',
    'Bohrium atoms last only fractions of a second before decaying.',
  ),
  ChemicalElement(
    108,
    'Hs',
    'Hassium',
    277.0,
    'transition',
    'A synthetic element named after the German state of Hesse.',
    'Only a few dozen atoms of hassium have ever been produced.',
  ),
  ChemicalElement(
    109,
    'Mt',
    'Meitnerium',
    276.0,
    'transition',
    'Named after physicist Lise Meitner, who discovered nuclear fission.',
    'Lise Meitner was nominated for the Nobel Prize multiple times but never won.',
  ),
  ChemicalElement(
    110,
    'Ds',
    'Darmstadtium',
    281.0,
    'transition',
    'A synthetic element named after Darmstadt, Germany.',
    'Darmstadtium was first created in 1994 and exists for only milliseconds.',
  ),
  ChemicalElement(
    111,
    'Rg',
    'Roentgenium',
    280.0,
    'transition',
    'Named after Wilhelm Röntgen, discoverer of X-rays.',
    'Roentgenium\'s most stable isotope has a half-life of only 26 seconds.',
  ),
  ChemicalElement(
    112,
    'Cn',
    'Copernicium',
    285.0,
    'transition',
    'Named after astronomer Nicolaus Copernicus.',
    'Copernicium may behave more like a noble gas than a metal at room temperature.',
  ),
  ChemicalElement(
    113,
    'Nh',
    'Nihonium',
    284.0,
    'post',
    'Named after Japan (Nihon) — the first element discovered in Asia.',
    'Nihonium was discovered by Japanese scientists at RIKEN in 2004.',
  ),
  ChemicalElement(
    114,
    'Fl',
    'Flerovium',
    289.0,
    'post',
    'Named after the Flerov Laboratory of Nuclear Reactions in Russia.',
    'Flerovium may have properties more like a noble gas than a metal.',
  ),
  ChemicalElement(
    115,
    'Mc',
    'Moscovium',
    288.0,
    'post',
    'Named after the Moscow region of Russia.',
    'Moscovium was first synthesized in 2003 in a US-Russian collaboration.',
  ),
  ChemicalElement(
    116,
    'Lv',
    'Livermorium',
    293.0,
    'post',
    'Named after the Lawrence Livermore National Laboratory in California.',
    'Livermorium is so unstable it decays almost instantly after being created.',
  ),
  ChemicalElement(
    117,
    'Ts',
    'Tennessine',
    294.0,
    'halogen',
    'Named after Tennessee, where key research institutions contributed to its discovery.',
    'Tennessine is the second heaviest element known.',
  ),
  ChemicalElement(
    118,
    'Og',
    'Oganesson',
    294.0,
    'noble',
    'The heaviest and most recently named element, named after physicist Yuri Oganessian.',
    'Oganesson may not behave like a noble gas despite being in that group.',
  ),
];
